### ISSUE TITLE
The package should depend on psr/cache instead of implementing the interfaces on its own

### ISSUE THREAD

**Issue by stof** [gpupo/cache#6]
Defining the interface yourselves and replacing the original package is a bad idea, especially given that the phpdoc of your interfaces don't match the actual PSR (return values for most method are booleans, not a fluent interface).

Please either upgrade your package to actually respect PSR-6, or mark it as abandoned on Packagist so that people looking for a PSR-6 implement know that they should go elsewhere.

**Comment by gpupo** [comment]
Yes, it's a bad idea, but it was the alternative to publish this package before the release of official PSR.
