### ISSUE TITLE
Missing Methods from Psr\Cache\CacheItemInterface

### ISSUE THREAD

**Issue by benjamin-carl** [gpupo/cache#7]
Hi @gpupo 

any plans on updating the library to match the PSR-6 specs? 

These two methods are missing in your implementation:

    public function expiresAt($expiration);
    @see https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L89

    public function expiresAfter($time);
    @see https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L104

Please let me know. I use your implementation in a demo and in unit-tests for https://github.com/clickalicious/caching-middleware but now the dependency is broken.

I can also do the work and send you a PR for the changes if u like.

**Comment by gpupo** [comment]
Hi @benjamin-carl !

Check release 1.3.1 => https://github.com/gpupo/cache/releases/tag/1.3.1 

Please, implement the methods :)
